services:
  db:
    image: postgres:16-alpine
    container_name: todo-db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes: 
  pgdata:
